# Generated by Django 4.2 on 2023-04-26 11:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_clientes_alter_contacto_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField()),
                ('cant_pzas', models.IntegerField(null=True)),
                ('descripcion', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
